services:
  - type: web
    name: mastewal
    env: node
    region: oregon
    buildCommand: cd client && npm install && npm run build && cd ../server && npm install && ls -la ../client/dist/
    startCommand: node server/index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: GEMINI_API_KEY
        sync: false
