services:
  - type: web
    name: mastewal
    env: node
    region: oregon
    buildCommand: npm install --prefix client && npm run build --prefix client && npm install --prefix server
    startCommand: node server/index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: GEMINI_API_KEY
        sync: false
